<#
.SYNOPSIS
    Produces a pre-configured copy of the PowerSyncPro Migration Agent MSI with
    the PSK and URL properties baked into the Property table, so the agent can
    be installed by double-click or plain "msiexec /i" with no parameters.

.DESCRIPTION
    The PowerSyncPro Migration Agent MSI is normally installed with two public
    properties on the command line:

        msiexec /i PSPMigrationAgentInstaller.msi /qn PSK="<psk>" URL="https://<server>/Agent"

    This script clones the PowerSyncPro MSI and writes those two values into the
    MSI Property table as defaults, using the same Windows Installer COM / MSI-SQL
    mechanism PowerSyncPro's own PSP-CreateMST.ps1 uses to build its GPO
    transform. The output is a standalone MSI intended for manual /
    technician-assisted installs where passing flags is impractical.

    Command-line properties still override the baked-in values, so the
    customized MSI can also be installed with explicit PSK/URL if ever needed.

    The script also stamps a new PackageCode (Summary Information revision
    GUID) into the copy, per Windows Installer rules for modified packages,
    so the customized MSI is never confused with the original in the local
    installer cache.

    Notes and caveats:
      - Baking the values breaks PowerSyncPro's Authenticode signature on the
        copy. Fine for manual installs; environments enforcing signed-MSI
        policies (AppLocker/WDAC) must use the original MSI plus parameters.
      - The PSK is stored in the MSI in plain text and is trivially
        extractable. Treat each customized MSI as a credential and scope it
        per customer/site.
      - The output is tied to the agent version it was built from. Re-run
        against each new PowerSyncPro MSI release.

.NOTES
    Author : Jamie Richard - PowerSyncPro
    Runs on: Windows PowerShell 5.1 or later. No third-party dependencies
             (uses the built-in WindowsInstaller.Installer COM object).
    MSI property names per PowerSyncPro KB:
      PSK - pre-shared key generated by the PSP server
      URL - agent registration endpoint, e.g. https://<server>/Agent

.PARAMETER MSIPath
    Path to the source (or, with -Verify, target) MSI.

.PARAMETER PSKValue
    Pre-shared key to bake in.

.PARAMETER URLValue
    Agent registration endpoint to bake in, e.g. https://psp.contoso.com/Agent
    Baked in exactly as supplied. It is normally the /Agent endpoint, and the
    script warns if it does not end in /Agent, but the value is never rewritten -
    a custom reverse proxy may expose the endpoint at a different path.

.PARAMETER PollingInterval
    Agent polling interval in seconds, baked in as POLLING_INTERVAL.
    Default: 60 (the agent's own default).

.PARAMETER Silent
    Make the baked MSI install with a progress bar and no wizard prompts even
    when double-clicked, by clearing its InstallUISequence table. The install
    still runs fully (all work is in the execute sequence); only the interactive
    dialogs are removed. Equivalent user experience to msiexec /qb. The UAC
    elevation prompt still appears.

.PARAMETER OutputPath
    Where to write the customized MSI. Default: alongside the source, named
    <basename>-<ProductVersion>-custom.msi

.PARAMETER Force
    Overwrite OutputPath if it already exists.

.PARAMETER Verify
    Do not build anything; open the given MSI read-only and report its
    identity, Authenticode signature status, and any baked-in PSK / URL /
    POLLING_INTERVAL values.

.EXAMPLE
    .\MsiCustomizer.ps1 -MSIPath .\PSPMigrationAgentInstaller.msi -PSKValue "abc123" -URLValue "https://psp.contoso.com/Agent"

.EXAMPLE
    .\MsiCustomizer.ps1 -MSIPath .\PSPMigrationAgentInstaller.msi -PSKValue "abc123" -URLValue "https://psp.contoso.com" -PollingInterval 300 -Silent

.EXAMPLE
    .\MsiCustomizer.ps1 -MSIPath .\PSPMigrationAgentInstaller-1.5.0-custom.msi -Verify
#>

[CmdletBinding(DefaultParameterSetName = 'Build')]
param(
    [Parameter(Mandatory = $true, ParameterSetName = 'Build', Position = 0)]
    [Parameter(Mandatory = $true, ParameterSetName = 'Verify', Position = 0)]
    [ValidateNotNullOrEmpty()]
    [string]$MSIPath,

    [Parameter(Mandatory = $true, ParameterSetName = 'Build')]
    [ValidateNotNullOrEmpty()]
    [string]$PSKValue,

    [Parameter(Mandatory = $true, ParameterSetName = 'Build')]
    [ValidateNotNullOrEmpty()]
    [string]$URLValue,

    [Parameter(ParameterSetName = 'Build')]
    [ValidateRange(1, 86400)]
    [int]$PollingInterval = 60,

    [Parameter(ParameterSetName = 'Build')]
    [switch]$Silent,

    [Parameter(ParameterSetName = 'Build')]
    [string]$OutputPath,

    [Parameter(ParameterSetName = 'Build')]
    [switch]$Force,

    [Parameter(Mandatory = $true, ParameterSetName = 'Verify')]
    [switch]$Verify
)

$ErrorActionPreference = 'Stop'

#region --- COM helpers (WindowsInstaller.Installer is late-bound; PS 5.1 needs InvokeMember) ---
function Invoke-ComMethod {
    param($Object, [string]$Name, [object[]]$Arguments = @())
    return $Object.GetType().InvokeMember($Name,
        [System.Reflection.BindingFlags]::InvokeMethod, $null, $Object, $Arguments)
}

function Get-ComProperty {
    param($Object, [string]$Name, [object[]]$Arguments = @())
    return $Object.GetType().InvokeMember($Name,
        [System.Reflection.BindingFlags]::GetProperty, $null, $Object, $Arguments)
}

function Set-ComProperty {
    param($Object, [string]$Name, [object[]]$Arguments)
    return $Object.GetType().InvokeMember($Name,
        [System.Reflection.BindingFlags]::SetProperty, $null, $Object, $Arguments)
}

function Release-ComObject {
    param($Object)
    if ($null -ne $Object) {
        [void][System.Runtime.InteropServices.Marshal]::ReleaseComObject($Object)
    }
}
#endregion

#region --- MSI database helpers ---
function Get-MsiPropertyTable {
    # Returns a hashtable of the full Property table of an MSI.
    param([string]$Path)
    $installer = New-Object -ComObject WindowsInstaller.Installer
    $db = $null; $view = $null
    $props = @{}
    try {
        $db = Invoke-ComMethod $installer 'OpenDatabase' @($Path, 0)   # 0 = read-only
        $view = Invoke-ComMethod $db 'OpenView' @('SELECT `Property`, `Value` FROM `Property`')
        Invoke-ComMethod $view 'Execute' | Out-Null
        while ($true) {
            $rec = Invoke-ComMethod $view 'Fetch'
            if ($null -eq $rec) { break }
            $name = Get-ComProperty $rec 'StringData' @(1)
            $value = Get-ComProperty $rec 'StringData' @(2)
            $props[$name] = $value
            Release-ComObject $rec
        }
    }
    finally {
        if ($null -ne $view) { Invoke-ComMethod $view 'Close' | Out-Null }
        Release-ComObject $view
        Release-ComObject $db
        Release-ComObject $installer
        [GC]::Collect(); [GC]::WaitForPendingFinalizers()
    }
    return $props
}

function Set-MsiProperty {
    # UPDATE if the property row exists, INSERT if not (same logic as the
    # PowerSyncPro's PSP-CreateMST.ps1). The value is passed as a query parameter
    # because MSI-SQL string literals have no quote-escape mechanism.
    param($Installer, $Database, [string]$Name, [string]$Value)
    $view = Invoke-ComMethod $Database 'OpenView' @(("SELECT ``Value`` FROM ``Property`` WHERE ``Property``='{0}'" -f $Name))
    Invoke-ComMethod $view 'Execute' | Out-Null
    $existing = Invoke-ComMethod $view 'Fetch'
    Invoke-ComMethod $view 'Close' | Out-Null
    Release-ComObject $view

    if ($null -ne $existing) {
        Release-ComObject $existing
        $sql = "UPDATE ``Property`` SET ``Value``=? WHERE ``Property``='{0}'" -f $Name
    }
    else {
        $sql = "INSERT INTO ``Property`` (``Property``, ``Value``) VALUES ('{0}', ?)" -f $Name
    }

    $record = Invoke-ComMethod $Installer 'CreateRecord' @(1)
    Set-ComProperty $record 'StringData' @(1, $Value)

    $view = Invoke-ComMethod $Database 'OpenView' @($sql)
    Invoke-ComMethod $view 'Execute' @($record) | Out-Null
    Invoke-ComMethod $view 'Close' | Out-Null
    Release-ComObject $view
    Release-ComObject $record
}
#endregion

#region --- Resolve and sanity-check input ---
$msiFull = (Resolve-Path -Path $MSIPath).ProviderPath
if (-not (Test-Path -Path $msiFull -PathType Leaf)) {
    throw "MSI not found: $msiFull"
}

$sourceProps = Get-MsiPropertyTable -Path $msiFull
$productName = $sourceProps['ProductName']
$productVersion = $sourceProps['ProductVersion']

Write-Host ("MSI            : {0}" -f $msiFull)
Write-Host ("ProductName    : {0}" -f $productName)
Write-Host ("ProductVersion : {0}" -f $productVersion)
Write-Host ("ProductCode    : {0}" -f $sourceProps['ProductCode'])
#endregion

#region --- Verify mode ---
if ($PSCmdlet.ParameterSetName -eq 'Verify') {
    $sig = Get-AuthenticodeSignature -FilePath $msiFull
    Write-Host ("Signature      : {0}" -f $sig.Status)
    Write-Host ""
    if ($sourceProps.ContainsKey('PSK')) {
        Write-Host ("PSK            : {0}" -f $sourceProps['PSK']) -ForegroundColor Green
    }
    else {
        Write-Host "PSK            : (not baked in)" -ForegroundColor Yellow
    }
    if ($sourceProps.ContainsKey('URL')) {
        Write-Host ("URL            : {0}" -f $sourceProps['URL']) -ForegroundColor Green
    }
    else {
        Write-Host "URL            : (not baked in)" -ForegroundColor Yellow
    }
    if ($sourceProps.ContainsKey('POLLING_INTERVAL')) {
        Write-Host ("POLLING_INTERVAL : {0}" -f $sourceProps['POLLING_INTERVAL']) -ForegroundColor Green
    }
    else {
        Write-Host "POLLING_INTERVAL : (not baked in - agent default 60)" -ForegroundColor Yellow
    }
    return
}
#endregion

#region --- Build mode ---
if ($URLValue -notmatch '^https://') {
    Write-Warning "URL does not start with https:// - the agent registration endpoint is normally HTTPS."
}

# The agent normally registers against a /Agent endpoint, but the URL is baked
# in exactly as given - never rewritten. A customized reverse proxy may expose
# that endpoint at a different path (even the site root), so silently appending
# /Agent could corrupt a valid URL. Warn if it looks unusual, but leave it alone.
if ($URLValue -notmatch '/agent/?$') {
    Write-Warning "URL does not end in /Agent - baking it verbatim. Confirm this is correct if the server uses a custom reverse-proxy path."
}

if ([string]::IsNullOrEmpty($OutputPath)) {
    $baseName = [System.IO.Path]::GetFileNameWithoutExtension($msiFull)
    $dir = [System.IO.Path]::GetDirectoryName($msiFull)
    $OutputPath = Join-Path $dir ("{0}-{1}-custom.msi" -f $baseName, $productVersion)
}
if (Test-Path -Path $OutputPath) {
    if ($Force) {
        Remove-Item -Path $OutputPath -Force
    }
    else {
        throw "Output file already exists: $OutputPath (use -Force to overwrite)"
    }
}

Copy-Item -Path $msiFull -Destination $OutputPath
$outFull = (Resolve-Path -Path $OutputPath).ProviderPath
Write-Host ""
Write-Host ("Writing        : {0}" -f $outFull)

$installer = $null; $db = $null; $sumInfo = $null
try {
    $installer = New-Object -ComObject WindowsInstaller.Installer
    $db = Invoke-ComMethod $installer 'OpenDatabase' @($outFull, 1)   # 1 = transact

    Set-MsiProperty -Installer $installer -Database $db -Name 'PSK' -Value $PSKValue
    Set-MsiProperty -Installer $installer -Database $db -Name 'URL' -Value $URLValue
    Set-MsiProperty -Installer $installer -Database $db -Name 'POLLING_INTERVAL' -Value $PollingInterval.ToString()

    if ($Silent) {
        # Documented Windows Installer behavior: when a full UI is requested
        # (e.g. a double-click) but the InstallUISequence table is empty, the
        # wizard dialogs are skipped and the install runs the InstallExecuteSequence
        # with a reduced UI - a progress bar only. Verified for this package that
        # every property-setting action in the UI sequence (SetFIRST_INSTALL,
        # SetUPGRADING, etc.) is also scheduled in InstallExecuteSequence, so no
        # install behavior is lost by clearing the UI sequence.
        $view = Invoke-ComMethod $db 'OpenView' @('DELETE FROM `InstallUISequence`')
        Invoke-ComMethod $view 'Execute' | Out-Null
        Invoke-ComMethod $view 'Close' | Out-Null
        Release-ComObject $view
    }

    # New PackageCode (Summary Information property 9, Revision Number) so the
    # modified package is distinct from the PowerSyncPro original per MSI rules.
    $newPackageCode = '{' + [guid]::NewGuid().ToString().ToUpper() + '}'
    $sumInfo = Get-ComProperty $db 'SummaryInformation' @(1)
    Set-ComProperty $sumInfo 'Property' @(9, $newPackageCode)
    Invoke-ComMethod $sumInfo 'Persist' | Out-Null

    Invoke-ComMethod $db 'Commit' | Out-Null
    Write-Host ("PackageCode    : {0}" -f $newPackageCode)
}
finally {
    Release-ComObject $sumInfo
    Release-ComObject $db
    Release-ComObject $installer
    [GC]::Collect(); [GC]::WaitForPendingFinalizers()
    [GC]::Collect(); [GC]::WaitForPendingFinalizers()
}

# Read the finished MSI back and confirm the values landed.
$checkProps = Get-MsiPropertyTable -Path $outFull
$ok = $true
if ($checkProps['PSK'] -ne $PSKValue) { $ok = $false }
if ($checkProps['URL'] -ne $URLValue) { $ok = $false }
if ($checkProps['POLLING_INTERVAL'] -ne $PollingInterval.ToString()) { $ok = $false }

Write-Host ""
if ($ok) {
    Write-Host "SUCCESS - baked-in values verified:" -ForegroundColor Green
    Write-Host ("  PSK              = {0}" -f $checkProps['PSK'])
    Write-Host ("  URL              = {0}" -f $checkProps['URL'])
    Write-Host ("  POLLING_INTERVAL = {0}" -f $checkProps['POLLING_INTERVAL'])
    Write-Host ""
    Write-Host "Install with:  msiexec /i `"$outFull`" /qn /L*V `"C:\Temp\PSP-Agent-Install.log`""
    Write-Host "(or double-click - no parameters needed)"
    Write-Host ""
    Write-Host "Reminder: the copy no longer carries a valid PowerSyncPro signature, and the" -ForegroundColor Yellow
    Write-Host "PSK inside it is extractable - distribute per customer/site only." -ForegroundColor Yellow
}
else {
    throw "Verification failed - read-back of $outFull did not return the expected PSK/URL/POLLING_INTERVAL values."
}
#endregion
